### ISSUE TITLE
Problem to Mask R-CNN

### ISSUE THREAD

**Issue by a22764288** [BerkeleyAutomation/sd-maskrcnn#10]
The third modification of the Mask R-CNN in your paper:

 We modify the network input to zero-pad the 512x384 pixel images in WISDOM-Sim to 512x512 images
and set the region proposal network **anchor scales and ratios to correspond to the 512x512 image size**.

Could you please tell me what SCALES and RATIOS of anchors did you use? Thanks.

**Comment by mjd3** [comment]
We've actually tried several anchor ratios and scales, although in the end, we found these did not have a great effect on the performance of the network. The following are the default values:
RPN_ANCHOR_SCALES = (32, 64, 128, 256, 512)
RPN_ANCHOR_RATIOS = [0.5, 1, 2]

We tried:
RPN_ANCHOR_SCALES = (8, 16, 32, 64, 128)
RPN_ANCHOR_RATIOS = [0.25, 0.5, 1, 1.5, 2]
because, in general, our instances take a smaller percentage of the image than the typical COCO image and our objects can have varied geometry (see supplementary material for more info on this). But again, we didn't get much of a performance increase from this.
