### ISSUE TITLE
generate include rgb

### ISSUE THREAD

**Issue by trevor-taeyeop** [BerkeleyAutomation/sd-maskrcnn#38]
Hi, Thank you for sharing a good works. 
I have very simple questions.

1. Have you tried training using WISDOM-Real, WISDOM-SIM Both, Is it better than using one dataset??

2. In WIDSOM-sim,
Is it possible to generate not only depth image but also generate the RGB image in your method?? 

Thanks.

**Comment by mjd3** [comment]
Hi @trevor-taeyeop! 

In fact, we have tried training on WISDOM-Sim and then finetuning on the train images of WISDOM-Real - this yields better performance (as one might expect) by about 5% in both AP and AR on high-res images and 15% in both AP and AR in low-res images (the difference is bigger here since our synthetic data models the high-res camera). However, in the paper, we elected to focus on the results without any real data, as we felt the network still performed quite well and required no human effort. As for your second question, #40 should address that; please let me know if that works for you!

**Comment by mjd3** [comment]
Closing this for now; can reopen if there are issues with generating RGB images.
