### ISSUE TITLE
Unable to normalize depth image for inference

### ISSUE THREAD

**Issue by aitorgutierrez** [BerkeleyAutomation/sd-maskrcnn#42]
Hello!

I am testing your inference part with your model and my bin-picking scene using a Photoneo.
I am trying to normalize my deep image (TIF) generated using Phoxi software using the following code. The code is an adaptation for your function ( https://github.com/BerkeleyAutomation/perception/blob/c5c07f8e26964fd006db59d5b2d2385420eb7789/perception/image.py#L1478)
```python
data = skimage.io.imread('1_IMG_DepthMap.tif')
data = np.asarray(data, dtype="float32")

BINARY_IM_MAX_VAL = np.iinfo(np.uint8).max
max_val = BINARY_IM_MAX_VAL

min_depth = np.min(data)
max_depth = np.max(data)
depth_data = (data - min_depth) / (max_depth - min_depth)
depth_data = float(max_val) * depth_data.squeeze()
im_data = np.zeros([data.shape[0], data.shape[1], 3],dtype=np.uint8)

im_data[:, :, 0] = depth_data
im_data[:, :, 1] = depth_data
im_data[:, :, 2] = depth_data

final_image=im_data.astype(np.uint8)
skimage.io.imsave('test.png', im_data)
```
I am trying to have similar depth images as you have in your WISDOM REAL dataset ( for example wisdom-real/high-res/depth_ims/image_000000.png). 

I save my normalized image (test.png) and it looks different from your normalized. The inference results are really bad. What is wrong  with the normalization?

**Comment by mjd3** [comment]
@aitorgutierrez Sorry for the delayed response! I think the issue here is coming from your min_depth and max_depth values. While you use the min and max values from each image, the images used in training actually have constant values (the MIN_DEPTH and MAX_DEPTH values [here](https://github.com/BerkeleyAutomation/perception/blob/c5c07f8e26964fd006db59d5b2d2385420eb7789/perception/constants.py#L8)). That's likely what's causing the issue.
