### ISSUE TITLE
Where is the coco pretrained Resnet35 network?

### ISSUE THREAD

**Issue by zeal-github** [BerkeleyAutomation/sd-maskrcnn#43]
Thanks for your work!
I think you use a self-modify resnet35 as the backbone. But I cannot find the coco pretrained model or the download link in this repo? Can you post the link here?

**Comment by mjd3** [comment]
@zeal-github For our network, we used a ResNet 35 backbone but trained from scratch (i.e., random weight initialization). So our trained model is available [here](https://berkeley.box.com/shared/static/obj0b2o589gc1odr2jwkx4qjbep11t0o.h5), but since we did not finetune a model that was originally trained on COCO, we do not have weights for that. For our baselines, we used a ResNet 50 backbone model that was pretrained on COCO and then finetuned. You can find that model [here](https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5) or use the 'coco' argument in the [training config file](https://github.com/BerkeleyAutomation/sd-maskrcnn/blob/75f2a81108c9e74702f831f60fcef8c5e903c8ab/cfg/train.yaml#L3), which will automatically download the weights for you. Hope that helps!
