### ISSUE TITLE
 Object ycbXXXXX fell out of the workspace!

### ISSUE THREAD

**Issue by aitorgutierrez** [BerkeleyAutomation/sd-maskrcnn#53]
Hi!

I am generating my custom dataset using your objects and I am usually getting this error with several obejcts

> HeapStateSpace WARNING  Obj too big, skipping .....
> HeapStateSpace WARNING  Object ycb~056_tennis_ball fell out of the workspace!
> HeapStateSpace WARNING  Object ycb~037_scissors fell out of the workspace!
> HeapStateSpace WARNING  Object ycb~077_rubiks_cube fell out of the workspace!
> HeapStateSpace WARNING  Object ycb~012_strawberry fell out of the workspace!
> HeapStateSpace WARNING  Object ycb~010_potted_meat_can fell out of the workspace!
> HeapStateSpace WARNING  Object ycb~036_wood_block fell out of the workspace!
> HeapStateSpace WARNING  Object ycb~041_small_marker fell out of the workspace!

How can I solve it?

**Comment by mjd3** [comment]
Hi @aitorgutierrez,

This warning is usually ok (and expected) since it happens when objects are dropped, but roll out of the range of the camera image. If it only happens a few times per heap, I wouldn't worry about it. If all of the objects are falling out of the workspace, try running with debug on and see if the objects are falling through the table.
