### ISSUE TITLE
Is there a way to add the same object multiple times

### ISSUE THREAD

**Issue by FrederikVanEecke** [BerkeleyAutomation/sd-maskrcnn#55]
I'm trying to fill a bin with many objects, for this I have 1 object within my datasets/objects/meshes directory and a want to add it many times. How can this be done? The original code only allows you to add some objects from this directory once?

**Comment by mjd3** [comment]
Hey @FrederikVanEecke,

Sorry for the delayed response! There is currently no way of supporting this, but I think it would be relatively easy to add. Maybe changing this [`permutation`](https://github.com/BerkeleyAutomation/sd-maskrcnn/blob/75f2a81108c9e74702f831f60fcef8c5e903c8ab/sd_maskrcnn/envs/state_spaces.py#L232) to a [`choice`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html) with `replace=True` could be one way? Some of the other code may need to be modified to support that change as well. I'd gladly accept a PR; otherwise I may be able to implement this but am currently a bit swamped. Thanks for your interest in the project!

**Comment by mjd3** [comment]
Had some time to implement this in #56; let me know if you run into any issues!
