### ISSUE TITLE
Depth image normalization

### ISSUE THREAD

**Issue by a22764288** [BerkeleyAutomation/sd-maskrcnn#6]
Can you tell me how your Wisdom-Real dataset depth image normalize to 0~255?
In other words, how you normalize original 16 bits depth image to 8 bit depth image?

I need to know it so that I can train and test using the data collected by me,
Thanks for your assistance.

**Comment by mjd3** [comment]
In our setup, we actually record 32 bit float depth images, then rescale them to 8-bit PNGs using the following function: https://github.com/BerkeleyAutomation/perception/blob/c5c07f8e26964fd006db59d5b2d2385420eb7789/perception/image.py#L1478
In this case, MIN_DEPTH = 0.25 and MAX_DEPTH = 1.25 (in meters) since these numbers described the min and max distances we expected objects could be recorded at. Hope that helps and let me know if you have more questions!
